development:
  adapter: mysql2
  encoding: utf8
  database: weixin
  pool: 5
  username: root
  password: shichao
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  database: weixin
  pool: 5
  username: root
  password: shichao
  socket: /var/run/mysqld/mysqld.sock
